version: '3'

services:
  frontend:
    build: .
    command: yarn start
    volumes:
      - .:/usr/frontend
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API: '${REACT_APP_API}'
    depends_on:
      - backend
  backend:
    build: ../be
    command: yarn start
    volumes:
      - ../be:/usr/backend
    ports:
      - '${PORT_BE}:${PORT_BE}'
    environment:
      PORT_BE: '${PORT_BE}'
      DATABASE_URL: '${DATABASE_URL}'
