version: '3'

services:
  frontend:
    build: .
    command: yarn start
    volumes:
      - ./fe
      - /fe/node_modules
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API: '${REACT_APP_API}'
    depends_on:
      - backend
  backend:
    build: ../be
    command: yarn start
    volumes:
      - ./be
      - /be/node_modules
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: '${PORT}'
      DATABASE_URL: '${DATABASE_URL}'
